### ISSUE TITLE
Submitting a string for court_id throws a server error in Elasticsearch

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1154]
https://beta-api.capapi.org/v1/cases/?page_size=10&court_id=mass

```
GET http://localhost:9200/cases/doc/_search [status:400 request:0.016s]
2019-08-28 19:19:43,688 ERROR module=log, process_id=20251, Internal Server Error: /v1/cases/
Traceback (most recent call last):
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/generics.py", line 173, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/usr/local/share/capstone/capstone/capapi/pagination.py", line 188, in paginate_queryset
    self.resp = resp = self._paginate_queryset(queryset, request, view)
  File "/usr/local/share/capstone/capstone/capapi/pagination.py", line 300, in _paginate_queryset
    resp = queryset[:self.page_size+1].execute()
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/elasticsearch_dsl/search.py", line 679, in execute
    **self._params
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: {\n  "bool" : {\n    "filter" : [\n      {\n        "terms" : {\n          "court.id" : [\n            "mass"\n          ],\n          "boost" : 1.0\n        }\n      }\n    ],\n    "adjust_pure_negative" : true,\n    "boost" : 1.0\n  }\n}')
```

**Comment by bensteinberg** [comment]
Closed in #1155
