### ISSUE TITLE
PDF generation errors

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#1183]
In a partial run of PDF generation,
```
32044038593570_redacted
32044038597167_redacted
32044038561619_redacted
32044032501678_redacted_2019_05_11_03.55.00
32044038592101_redacted_2016_10_08_18.30.00
32044038594784_redacted
32044038593620_redacted
32044038593547_redacted
32044038595088_redacted
32044038594859_redacted_2019_04_30_05.04.00
32044038600573_redacted
```
produced errors like this in the worker logs:
```
    [2019-09-23 14:29:24,908: ERROR/ForkPoolWorker-31] Task scripts.make_pdf.make_pdf[e1ce1625-46cb-4da3-a538-1951650eb65e] raised unexpected: ValueError('max() arg is an empty sequence',)
    Traceback (most recent call last):
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
        R = retval = fun(*args, **kwargs)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/celery/app/trace.py", line 648, in __protected_call__
        return self.run(*args, **kwargs)
      File "/usr/local/share/capstone/capstone/scripts/make_pdf.py", line 205, in make_pdf
        baseline_offset = get_word_baseline_offset(text, style['metrics_font'], style['size'])
      File "/usr/local/share/capstone/capstone/scripts/make_pdf.py", line 58, in get_word_baseline_offset
        return max(get_baseline_offset(c, ttf_name, font_size) for c in set(word))
    ValueError: max() arg is an empty sequence
```

**Comment by bensteinberg** [comment]
(I thought we observed and fixed this already, but can't find the evidence.)

**Comment by bensteinberg** [comment]
I found the observation and discussion in Slack, but no fix. PR coming up shortly.
