### ISSUE TITLE
more PDF generation errors

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#1185]
Some volumes (74 listed below) are producing an error in the worker log that looks like 
```
    [2019-09-24 08:44:43,131: ERROR/ForkPoolWorker-1849] Task scripts.make_pdf.make_pdf[5ad7b69f-bee2-4edc-8b8c-723a2fe2efe1] raised unexpected: CalledProcessError(-6, ['pdftk', '/tmp/tmpp6ekbg9c/text.pdf', 'multibackground', '/tmp/tmpp6ekbg9c/tifs.pdf', 'output', '/tmp/tmpp6ekbg9c/combined.pdf'])
    Traceback (most recent call last):
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
        R = retval = fun(*args, **kwargs)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/celery/app/trace.py", line 648, in __protected_call__
        return self.run(*args, **kwargs)
      File "/usr/local/share/capstone/capstone/scripts/make_pdf.py", line 233, in make_pdf
        subprocess.check_call(['pdftk', str(text_pdf_path), 'multibackground', str(tif_pdf_path), 'output', str(combined_pdf_path)])
      File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['pdftk', '/tmp/tmpp6ekbg9c/text.pdf', 'multibackground', '/tmp/tmpp6ekbg9c/tifs.pdf', 'output', '/tmp/tmpp6ekbg9c/combined.pdf']' returned non-zero exit status -6
```
(A handful of volumes, to wit `NOTALEPH001811_redacted NOTALEPH000595_redacted NOTALEPH000597_redacted 32044110637378_redacted` produce `OSError(28, 'No space left on device')`, so we'll need to boost disk space, and it's possible that this is the underlying problem here as well.)
```
32044032500381_unredacted
32044038594651_unredacted
32044038594727_unredacted
32044038594800_unredacted
32044038597068_unredacted
32044038597514_unredacted
32044038607693_unredacted
32044038618823_unredacted
32044038619821_unredacted
32044038662862_unredacted
32044038665808_unredacted
32044038666715_unredacted
32044038670329_unredacted
32044038670725_unredacted
32044038670832_unredacted
32044038682977_unredacted
32044038683140_unredacted
32044038686689_unredacted
32044038687034_unredacted
32044038689105_unredacted
32044038693297_unredacted
32044038693339_unredacted
32044046857207_unredacted_2019_05_14_19.49.00
32044046858536_unredacted
32044046862074_unredacted
32044046898169_unredacted
32044046899316_unredacted
32044046905410_unredacted
32044046911715_unredacted
32044047010079_unredacted
32044047010103_unredacted
32044047012588_unredacted
32044047012711_unredacted
32044047018288_unredacted
32044047023684_unredacted
32044047023734_unredacted
32044047026851_unredacted
32044049857378_unredacted
32044049862410_unredacted
32044054435649_unredacted
32044057439218_unredacted
32044057439226_unredacted
32044057486144_unredacted
32044057486722_unredacted
32044057506099_unredacted
32044057506107_unredacted
32044057506115_unredacted
32044057619371_unredacted
32044057698375_unredacted
32044057700106_unredacted
32044057711731_unredacted
32044057716615_unredacted
32044061428231_unredacted
32044061428272_unredacted
32044061429312_unredacted
32044061429320_unredacted
32044061429346_unredacted
32044061429411_unredacted
32044061429437_unredacted
32044061429445_unredacted
32044061429460_unredacted
32044061429486_unredacted
32044061430393_unredacted
32044061430526_unredacted
32044061430658_unredacted
32044061430674_unredacted
32044061430682_unredacted
32044110637170_redacted
32044110637477_redacted
32044115974230_redacted
NOTALEPH000590_redacted
NOTALEPH000606_redacted
NOTALEPH000611_redacted
NOTALEPH001377_redacted
```

**Comment by bensteinberg** [comment]
I'm generating these locally, and so far they've all worked fine; I'll close this if they all finish OK.

**Comment by bensteinberg** [comment]
Running locally only went so far; I'm running this now on instances with 16G root drives.

**Comment by bensteinberg** [comment]
All 70,801 finished OK: 40,279 redacted and 30,522 unredacted.
