### ISSUE TITLE
Bulk data export: capdb.models.DoesNotExist: [Reporter|Jurisdiction] matching query does not exist.

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#1193]
A recent run of `fab bag_all_cases` appears to have worked fine except for two reporters and one jurisdiction:
```
S.C.L. (Rich.)
S.C. Eq. (Rich. Eq.)
United States
```
Trying to generate them with `fab bag_reporter:...` or `fab bag_jurisdiction:...` produces a traceback like
```
Traceback (most recent call last):
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/local/share/capstone/capstone/fabfile.py", line 420, in bag_jurisdiction
    jurisdiction = Jurisdiction.objects.get(name=name)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
capdb.models.DoesNotExist: Jurisdiction matching query does not exist.
```

**Comment by bensteinberg** [comment]
Ah, is `United States` now `U.S.`?

**Comment by bensteinberg** [comment]
Scratch that -- `United States` just finished. I'm still looking into the two reporters.

**Comment by bensteinberg** [comment]
Never mind -- 
```
    with EditLog(
         description='Combine reporters 909 and 1075 into just 1075, and 1076 and 919 into just 919. '
         'This combines the first and second run of S.C.L. (Rich.) and S.C. Eq. (Rich. Eq.), respectively. '
         'They are combined as they use the same numbering sequence -- see '
         'https://www.sccourts.org/courtreg/displayRule.cfm?ruleID=268.0&subRuleID=&ruleType=APP'
    ).record():
        for first_id, second_id in ((909, 1075), (1076, 919)):
            r1 = Reporter.objects.get(id=first_id)
            r2 = Reporter.objects.get(id=second_id)
            r2.start_year = r1.start_year
            r2.volume_count += r1.volume_count
            r2.hollis += r1.hollis
            r2.save()
            for v in r1.volumes.all():
                v.set_reporter(r2)
            r1.delete()
```
