### ISSUE TITLE
Migrations throw an error in Docker container

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#236]
```
$ docker-compose exec web fab init_db
[localhost] local: python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, capapi, capdb, contenttypes, sessions, tracking_tool
Running migrations:
  Applying capapi.0003_auto_20180403_0004... OK
  Applying capdb.0028_auto_20180319_2038... OK
  Applying capdb.0029_auto_20180320_1949... OK
  Applying capdb.0030_auto_20180321_1726... OK
  Applying capdb.0031_auto_20180329_2012... OK
  Applying capdb.0032_auto_20180409_0113... OK
[localhost] local: python manage.py migrate --database=tracking_tool
Operations to perform:
  Apply all migrations: admin, auth, authtoken, capapi, capdb, contenttypes, sessions, tracking_tool
Running migrations:
  Applying capapi.0003_auto_20180403_0004... OK
  Applying capdb.0028_auto_20180319_2038... OK
  Applying capdb.0029_auto_20180320_1949... OK
  Applying capdb.0030_auto_20180321_1726... OK
  Applying capdb.0031_auto_20180329_2012... OK
  Applying capdb.0032_auto_20180409_0113... OK
WARNING: temporal_tables extension is not installed. Versioning will be slower. See https://pgxn.org/dist/temporal_tables/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/fabric/main.py", line 762, in main
    *args, **kwargs
  File "/usr/local/lib/python3.6/site-packages/fabric/tasks.py", line 425, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python3.6/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/app/fabfile.py", line 104, in init_db
    migrate()
  File "/usr/local/lib/python3.6/site-packages/fabric/tasks.py", line 169, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/app/fabfile.py", line 120, in migrate
    update_postgres_env()
  File "/usr/local/lib/python3.6/site-packages/fabric/tasks.py", line 169, in __call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/app/fabfile.py", line 80, in update_postgres_env
    set_up_postgres.update_postgres_env()
  File "/app/scripts/set_up_postgres.py", line 37, in update_postgres_env
    cursor.execute((Path(settings.BASE_DIR) / "../services/postgres/versioning_function.sql").read_text())
  File "/usr/local/lib/python3.6/pathlib.py", line 1194, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/lib/python3.6/pathlib.py", line 1181, in open
    opener=self._opener)
  File "/usr/local/lib/python3.6/pathlib.py", line 1035, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/local/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/app/../services/postgres/versioning_function.sql'
```

**Comment by rebeccacremona** [comment]
Fixed in https://github.com/harvard-lil/capstone/pull/458
