### ISSUE TITLE
Server error on datamod when viewing admin list for CaseXML/PageXML

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#721]

**Comment by bensteinberg** [comment]
```
2018-11-28 19:18:39,587 ERROR module=exception, process_id=3266, Internal Server Error: /admin/capdb/pagexml/
Traceback (most recent call last):
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/contrib/admin/options.py", line 575, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1592, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/contrib/admin/options.py", line 706, in get_changelist_instance
    self,
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/contrib/admin/views/main.py", line 77, in __init__
    self.get_results(request)
  File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/contrib/admin/views/main.py", line 182, in get_results
    can_show_all = result_count <= self.list_max_show_all
TypeError: unorderable types: NoneType() <= int()
```
