### ISSUE TITLE
500 at a specific cursor, provided by us

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#727]
`https://api.case.law/v1/courts/?cursor=cD1BcHBlbGxhdGUrQ291cnQrb2YrU3VwZXJpb3IrQ291cnQrb2YrdGhlK1N0YXRlK29mK0NhbGlmb3JuaWE%3D`
`https://api.case.law/v1/courts/?cursor=cD1CYWtlcitDb3VudHkrQ2lyY3VpdCtDb3VydA%3D%3D`
`https://api.case.law/v1/courts/?cursor=cD1CbGFpcitDb3VudHkrT3JwaGFucyUyNytDb3VydA%3D%3D`
`https://api.case.law/v1/courts/?cursor=cD1CdXRsZXIrQ291bnR5K0NvdXJ0K29mJUMyJUEwQ29tbW9uJUMyJUEwUGxlYXM%3D`
`https://api.case.law/v1/courts/?cursor=cD1DaGFtcGFpZ24rQ291bnR5K0NpcmN1aXQrQ291cnQmbz0x`
`https://api.case.law/v1/courts/?cursor=cD1DbGFyaW9uK0NvdW50eStPcnBoYW5zJTI3K0NvdXJ0`
`https://api.case.law/v1/courts/?cursor=cD1Db2x1bWJpYStTdXBlcmlvcitDb3VydA%3D%3D`
`https://api.case.law/v1/courts/?cursor=cD1Db3VudHkrQ291cnQrb2YrTmV3K1lvcmsrTW9ucm9lK0NvdW50eSZvPTM%3D`
`https://api.case.law/v1/courts/?cursor=cD1Db3VudHkrQ291cnQrb2YrTmV3K1lvcmslMkMlQzIlQTBQdXRuYW0rQ291bnR5`
`https://api.case.law/v1/courts/?cursor=cD1Db3VydCtvZitHZW5lcmFsK1Nlc3Npb25zK29mK3RoZStQZWFjZQ%3D%3D`
`https://api.case.law/v1/courts/?cursor=cD1EYXJrZStDb3VudHkrTXVuaWNpcGFsK0NvdXJ0`
`https://api.case.law/v1/courts/?cursor=cD1EaXNjaXBsaW5hcnkrQm9hcmQrb2YrdGhlK1N1cHJlbWUrQ291cnQrb2YrUGVubnN5bHZhbmlh`
`https://api.case.law/v1/courts/?cursor=cD1FcmllK0NvdW50eStDb3VydCtvZitPeWVyK2FuZCtUZXJtaW5lciZvPTM%3D`
`https://api.case.law/v1/courts/?cursor=cD1Gb3Jlc3QrQ291bnR5K09ycGhhbnMlMjcrQ291cnQ%3D`
`https://api.case.law/v1/courts/?cursor=cD1HcmF2ZXMrQ2lyY3VpdCtDb3VydA%3D%3D`
`https://api.case.law/v1/courts/?cursor=cD1IZW5yeStDaXJjdWl0K0NvdXJ0`
`https://api.case.law/v1/courts/?cursor=cD1JbmRpYW5hK0NpcmN1aXQrQ291cnQmbz0y`
`https://api.case.law/v1/courts/?cursor=cD1KdXN0aWNlK0NvdXJ0K29mK1ZpbGxhZ2Urb2YrRWxtc2ZvcmQ%3D`
`https://api.case.law/v1/courts/?cursor=cD1MYWtlK0NvdW50eStDb3VydCtvZitDb21tb24rUGxlYXM%3D`
`https://api.case.law/v1/courts/?cursor=cD1MaWJlcnR5K0NvdW50eStTdXBlcmlvcitDb3VydA%3D%3D`
`https://api.case.law/v1/courts/?cursor=cD1NYWRpc29uK0NvdW50eStQcm9iYXRlK0NvdXJ0`
`https://api.case.law/v1/courts/?cursor=cD1NZXJjZXIrQ291bnR5K0NvdXJ0K0xhdytEaXZpc2lvbiZvPTE%3D`
`https://api.case.law/v1/courts/?cursor=cD1Nb25yb2UrQ291bnR5K0NvdXJ0K29mK05ldytZb3Jr`
`https://api.case.law/v1/courts/?cursor=cD1NdXNraW5ndW0rQ2lyY3VpdCtDb3VydA%3D%3D`
`https://api.case.law/v1/courts/?cursor=cD1OZXcrWW9yaytDYXl1Z2ErQ291bnR5K0NvdXJ0Jm89MQ%3D%3D`
`https://api.case.law/v1/courts/?cursor=cD1OZXcrWW9yaytDb3VudHkrQ291cnQlMkMrT25vbmRhZ2ErQ291bnR5`
`https://api.case.law/v1/courts/?cursor=cD1OZXcrWW9yaytDb3VydCtvZitTcGVjaWFsK1Nlc3Npb24mbz0z`
`https://api.case.law/v1/courts/?cursor=cD1OZXcrWW9yaytTdXByZW1lK2NvdXJ0Jm89MTQ%3D`

The last URL 500s

**Comment by bensteinberg** [comment]
```
    2018-12-03 14:36:27,088 ERROR module=exception, process_id=1056, Internal Server Error: /v1/courts/
    Traceback (most recent call last):
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/relations.py", line 376, in to_representation
        url = self.get_url(value, self.view_name, request, format)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/relations.py", line 314, in get_url
        return self.reverse(view_name, kwargs=kwargs, request=request, format=format)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/reverse.py", line 50, in reverse
        url = _reverse(viewname, args, kwargs, request, format, **extra)
      File "./capapi/resources.py", line 130, in api_reverse
        return django_hosts_reverse(viewname, args=args, kwargs=kwargs, host='api', scheme='http' if settings.DEBUG else 'https', **extra)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django_hosts/resolvers.py", line 186, in reverse
        current_app=current_app,
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/urls/base.py", line 90, in reverse
        return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/urls/resolvers.py", line 634, in _reverse_with_prefix
        raise NoReverseMatch(msg)
    django.urls.exceptions.NoReverseMatch: Reverse for 'court-detail' with keyword arguments '{'slug': ''}' not found. 2 pattern(s) tried: ['v1\\/courts/(?P<slug>[^/.]+)\\.(?P<format>[a-z0-9]+)/?$', 'v1\\/courts/(?P<slug>[^/.]+)/$']
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
        response = self.process_exception_by_middleware(e, request)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
        return view_func(*args, **kwargs)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/viewsets.py", line 103, in view
        return self.dispatch(request, *args, **kwargs)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
        response = self.handle_exception(exc)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
        self.raise_uncaught_exception(exc)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
        response = handler(request, *args, **kwargs)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/mixins.py", line 45, in list
        return self.get_paginated_response(serializer.data)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/serializers.py", line 765, in data
        ret = super(ListSerializer, self).data
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/serializers.py", line 262, in data
        self._data = self.to_representation(self.instance)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/serializers.py", line 683, in to_representation
        self.child.to_representation(item) for item in iterable
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/serializers.py", line 683, in <listcomp>
        self.child.to_representation(item) for item in iterable
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/serializers.py", line 527, in to_representation
        ret[field.field_name] = field.to_representation(attribute)
      File "/usr/local/share/.virtualenvs/capstone/lib/python3.5/site-packages/rest_framework/relations.py", line 391, in to_representation
        raise ImproperlyConfigured(msg % self.view_name)
    django.core.exceptions.ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "court-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
```

**Comment by bensteinberg** [comment]
After a data release this morning, this URL no longer 500s. We can reopen as necessary
