### ISSUE TITLE
django_partial_index is a blocker for upgrading to Django 2.1, let alone 2.2

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#873]
We use the latest release of `django_partial_index`, 0.5.2; see https://github.com/mattiaslinnap/django-partial-index/pull/14 where someone is getting a start on an upgrade.

The traceback on running `pytest` with Django 2.2 installed looks like this:
```
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/_pytest/config/__init__.py", line 55, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python3.5/site-packages/_pytest/config/__init__.py", line 180, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/usr/local/lib/python3.5/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.5/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python3.5/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/site-packages/_pytest/config/__init__.py", line 612, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python3.5/site-packages/_pytest/config/__init__.py", line 777, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/local/lib/python3.5/site-packages/_pytest/config/__init__.py", line 739, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/usr/local/lib/python3.5/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.5/site-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/site-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/site-packages/pytest_django/plugin.py", line 328, in pytest_load_initial_conftests
    _setup_django()
  File "/usr/local/lib/python3.5/site-packages/pytest_django/plugin.py", line 216, in _setup_django
    django.setup()
  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/app/capdb/models.py", line 750, in <module>
    class CaseMetadata(models.Model):
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 315, in __new__
    new_class._prepare()
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 367, in _prepare
    index.set_name_with_model(cls)
  File "/usr/local/lib/python3.5/site-packages/partial_index/index.py", line 146, in set_name_with_model
    '%s_%s' % (self._hash_generator(*hash_data), self.suffix),
AttributeError: 'PartialIndex' object has no attribute '_hash_generator'
```

**Comment by jcushman** [comment]
2.2 adds a feature that might replace partial_indexes entirely -- maybe we can use that?

https://docs.djangoproject.com/en/2.2/ref/models/indexes/#django.db.models.Index.condition

**Comment by bensteinberg** [comment]
Thanks, trying out `condition` now.
